<?php

/*
 * Implementation of hook_menu()
 */
function sanjua_menu(){
	$items = array();

  $items['settings'] = array(
    'title' => t('General Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sanjua_settings_form'),
    'access callback' => TRUE,
		'access arguments' => array('access administration pages'),
		'file' => 'sanjua.admin.inc',
  );

  return $items;
}